from BaseClasses import Item
import typing

class ONIItem(Item):
    game: str = "Oxygen Not Included"

class ItemData(typing.NamedTuple):
    code: int
    count: int = 1
    progression: bool = False
    useful: bool = False
    trap: bool = False

oni_base_id = 57000

vanilla_research = {
    "Basic Farming": ItemData(oni_base_id + 0, progression=True),
    "Meal Preparation": ItemData(oni_base_id + 1, progression=True),
    "Agriculture": ItemData(oni_base_id + 2, progression=True),
    "Food Repurposing": ItemData(oni_base_id + 3, progression=True),
    "Ranching": ItemData(oni_base_id + 4, progression=True),
    "Animal Control": ItemData(oni_base_id + 5, progression=True),
    "Gourmet Meal Preparation": ItemData(oni_base_id + 6, progression=True),
    "Power Regulation": ItemData(oni_base_id + 7, progression=True),
    "Internal Combustion": ItemData(oni_base_id + 8, progression=True),
    "Fossil Fuels": ItemData(oni_base_id + 9, progression=True),
    "Plastic Manufacturing": ItemData(oni_base_id + 10, progression=True),
    "Valve Miniaturization": ItemData(oni_base_id + 11, progression=True),
    "Sound Amplifiers": ItemData(oni_base_id + 12, progression=True),
    "Advanced Power Regulation": ItemData(oni_base_id + 13, progression=True),
    "Low-Resistance Conductors": ItemData(oni_base_id + 14, progression=True),
    "Renewable Energy": ItemData(oni_base_id + 15, progression=True),
    "Employment": ItemData(oni_base_id + 16, progression=True),
    "Brute-Force Refinement": ItemData(oni_base_id + 17, progression=True),
    "Smart Storage": ItemData(oni_base_id + 18, progression=True),
    "Solid Transport": ItemData(oni_base_id + 19, progression=True),
    "Solid Control": ItemData(oni_base_id + 20, progression=True),
    "Solid Management": ItemData(oni_base_id + 21, progression=True),
    "Refined Renovations": ItemData(oni_base_id + 22, progression=True),
    "Smelting": ItemData(oni_base_id + 23, progression=True),
    "Superheated Forging": ItemData(oni_base_id + 24, progression=True),
    "Advanced Research": ItemData(oni_base_id + 25, progression=True),
    "Artificial Friends": ItemData(oni_base_id + 26, progression=True),
    "Robotic Tools": ItemData(oni_base_id + 27, progression=True),
    "Notification Systems": ItemData(oni_base_id + 28, progression=True),
    "Pharmacology": ItemData(oni_base_id + 29, progression=True),
    "Medical Equipment": ItemData(oni_base_id + 30, progression=True),
    "Pathogen Diagnostics": ItemData(oni_base_id + 31, progression=True),
    "Micro-Targeted Medicine": ItemData(oni_base_id + 32, progression=True),
    "Plumbing": ItemData(oni_base_id + 33, progression=True),
    "Air Systems": ItemData(oni_base_id + 34, progression=True),
    "Liquid-Based Refinement Processes": ItemData(oni_base_id + 35, progression=True),
    "Sanitation": ItemData(oni_base_id + 36, progression=True),
    "Flow Redirection": ItemData(oni_base_id + 37, progression=True),
    "Filtration": ItemData(oni_base_id + 38, progression=True),
    "Distillation": ItemData(oni_base_id + 39, progression=True),
    "Improved Plumbing": ItemData(oni_base_id + 40, progression=True),
    "Liquid Tuning": ItemData(oni_base_id + 41, progression=True),
    "Advanced Caffeination": ItemData(oni_base_id + 42, progression=True),
    "Ventilation": ItemData(oni_base_id + 43, progression=True),
    "Pressure Management": ItemData(oni_base_id + 44, progression=True),
    "Temperature Modulation": ItemData(oni_base_id + 45, progression=True),
    "HVAC": ItemData(oni_base_id + 46, progression=True),
    "Catalytics": ItemData(oni_base_id + 47, progression=True),
    "Decontamination": ItemData(oni_base_id + 48, progression=True),
    "Portable Gasses": ItemData(oni_base_id + 49, progression=True),
    "Improved Ventilation": ItemData(oni_base_id + 50, progression=True),
    "Hazard Protection": ItemData(oni_base_id + 51, progression=True),
    "Transit Tubes": ItemData(oni_base_id + 52, progression=True),
    "Jetpacks": ItemData(oni_base_id + 53, progression=True),
    "Interior Decor": ItemData(oni_base_id + 54, progression=True),
    "Artistic Expression": ItemData(oni_base_id + 55, progression=True),
    "Textile Production": ItemData(oni_base_id + 56, progression=True),
    "Home Luxuries": ItemData(oni_base_id + 57, progression=True),
    "Glass Blowing": ItemData(oni_base_id + 58, progression=True),
    "Environmental Appreciation": ItemData(oni_base_id + 59, progression=True),
    "Fine Art": ItemData(oni_base_id + 60, progression=True),
    "High Culture": ItemData(oni_base_id + 61, progression=True),
    "Renaissance Art": ItemData(oni_base_id + 62, progression=True),
    "New Media": ItemData(oni_base_id + 63, progression=True),
    "Monuments": ItemData(oni_base_id + 64, progression=True),
    "Smart Home": ItemData(oni_base_id + 65, progression=True),
    "Generic Sensors": ItemData(oni_base_id + 66, progression=True),
    "Parallel Automation": ItemData(oni_base_id + 67, progression=True),
    "Advanced Automation": ItemData(oni_base_id + 68, progression=True),
    "Computing": ItemData(oni_base_id + 69, progression=True),
    "Multiplexing": ItemData(oni_base_id + 70, progression=True),
    "Celestial Detection": ItemData(oni_base_id + 71, progression=True),
    "Introductory Rocketry": ItemData(oni_base_id + 72, progression=True),
    "Solid Fuel Combustion": ItemData(oni_base_id + 73, progression=True),
    "Hydrocarbon Combustion": ItemData(oni_base_id + 74, progression=True),
    "CryoFuel Combustion": ItemData(oni_base_id + 75, progression=True),
    "Solid Cargo": ItemData(oni_base_id + 76, progression=True),
    "Liquid and Gas Cargo": ItemData(oni_base_id + 77, progression=True),
    "Unique Cargo": ItemData(oni_base_id + 78, progression=True)
}

vanilla_care_packages = {
    "500kg Algae": ItemData(oni_base_id + 200),
    "1 Arbor Acorn": ItemData(oni_base_id + 201),
    "2 Blossom Seed": ItemData(oni_base_id + 202),
    "3 Briar Seed": ItemData(oni_base_id + 203),
    "2000kg Brine": ItemData(oni_base_id + 204),
    "3000kg Coal": ItemData(oni_base_id + 205),
    "3kg Curative Tablet": ItemData(oni_base_id + 206),
    "500kg Dirt": ItemData(oni_base_id + 207),
    "3000kg Fertilizer": ItemData(oni_base_id + 208),
    "1 Fungal Spore": ItemData(oni_base_id + 209),
    "1 Hatchling": ItemData(oni_base_id + 210),
    "3 Hatchling Egg": ItemData(oni_base_id + 211),
    "3 Joya Seed": ItemData(oni_base_id + 212),
    "3 Mirth leaf Seed": ItemData(oni_base_id + 213),
    "6kg Muckroot": ItemData(oni_base_id + 214),
    "5kg Nutrient Bar": ItemData(oni_base_id + 215),
    "1 Oxyfern Seed": ItemData(oni_base_id + 216),
    "100kg Oxylite": ItemData(oni_base_id + 217),
    "2 Pip Egg": ItemData(oni_base_id + 218),
    "1 Pipsqueak": ItemData(oni_base_id + 219),
    "1 Pokeshell Spawn": ItemData(oni_base_id + 220),
    "1 Puftlet": ItemData(oni_base_id + 221),
    "3 Puftlet Egg": ItemData(oni_base_id + 222),
    "1000kg Rust": ItemData(oni_base_id + 223),
    "2000kg Salt Water": ItemData(oni_base_id + 224),
    "3000kg Sand": ItemData(oni_base_id + 225),
    "1000kg Sandstone": ItemData(oni_base_id + 226),
    "1 Shine Nymph": ItemData(oni_base_id + 227),
    "3 Shine Nymph Egg": ItemData(oni_base_id + 228),
    "1 Snazzy Suit": ItemData(oni_base_id + 229),
    "2000kg Water": ItemData(oni_base_id + 230),
    "3kg Omelette": ItemData(oni_base_id + 231),
    "3kg Bristle Berry": ItemData(oni_base_id + 232),
    "4000kg Ice": ItemData(oni_base_id + 233),
    "3 Larva Egg": ItemData(oni_base_id + 234),
    "1 Balm Lily Seed": ItemData(oni_base_id + 235),
    "1 Drecklet": ItemData(oni_base_id + 236),
    "3 Drecklet Egg": ItemData(oni_base_id + 237),
    "3kg Fried Mushroom": ItemData(oni_base_id + 238),
    "8 Pacu": ItemData(oni_base_id + 239),
    "1 Pincha Pepper Seed": ItemData(oni_base_id + 240),
    "3 Shove Vole Egg": ItemData(oni_base_id + 241),
    "3 Thimble Reed Seed": ItemData(oni_base_id + 242),
    "1 Wort Seed": ItemData(oni_base_id + 243),
    "3kg Barbeque": ItemData(oni_base_id + 244),
    "1 Slickster Larva": ItemData(oni_base_id + 245),
    "3kg Spicy Tofu": ItemData(oni_base_id + 246),
    "1 Vole Pup": ItemData(oni_base_id + 247),
    "2000kg Copper Ore": ItemData(oni_base_id + 248),
    "2000kg Gold Amalgam": ItemData(oni_base_id + 249),
    "400kg Copper": ItemData(oni_base_id + 250),
    "400kg Iron": ItemData(oni_base_id + 251),
    "100kg Aluminum Ore": ItemData(oni_base_id + 252),
    "100kg Ethanol": ItemData(oni_base_id + 253),
    "200kg Glass": ItemData(oni_base_id + 254),
    "150kg Lime": ItemData(oni_base_id + 255),
    "500kg Plastic": ItemData(oni_base_id + 256),
    "100kg Steel": ItemData(oni_base_id + 257),
}

item_table = {
    **vanilla_research,
    **vanilla_care_packages,
    "Care Package Trap": ItemData(oni_base_id + 400, trap=True),
    "Colony Trap": ItemData(oni_base_id + 401, trap=True)
}

lookup_id_to_name: typing.Dict[int, str] = {data.code: item_name for item_name, data in item_table.items() if data.code}
