from typing import Dict, Set


vanilla_tech_tree: Dict[str, Set[str]] = {
  "Basic Farming": { "Meal Preparation" },
  "Meal Preparation": { "Agriculture", "Ranching" },
  "Agriculture": { "Food Repurposing", "Animal Control" },
  "Ranching": { "Animal Control" },
  "Animal Control": { "Gourmet Meal Preparation" },
  "Power Regulation": { "Internal Combustion" },
  "Internal Combustion": { "Fossil Fuels", "Sound Amplifiers", "Advanced Power Regulation" },
  "Fossil Fuels": { "Plastic Manufacturing" },
  "Plastic Manufacturing": { "Valve Miniaturization" },
  "Advanced Power Regulation": { "Low-Resistance Conductors", "Solid Transport" },
  "Low-Resistance Conductors": { "Renewable Energy" },
  "Employment": { "Brute-Force Refinement", "Advanced Research" },
  "Brute-Force Refinement": { "Smart Storage", "Refined Renovations", "Artificial Friends" },
  "Smart Storage": { "Solid Transport" },
  "Solid Control": { "Solid Management" },
  "Refined Renovations": { "Smelting" },
  "Smelting": { "Superheated Forging" },
  "Artificial Friends": { "Robotic Tools" },
  "Advanced Research": { "Artificial Friends", "Notification Systems", "Pathogen Diagnostics" },
  "Pharmacology": { "Medical Equipment" },
  "Medical Equipment": { "Pathogen Diagnostics" },
  "Pathogen Diagnostics": { "Micro-Targeted Medicine" },
  "Plumbing": { "Air Systems", "Sanitation", "Filtration" },
  "Air Systems": { "Liquid-Based Refinement Process" },
  "Sanitation": { "Flow Redirection" },
  "Filtration": { "Distillation", "Improved Plumbing" },
  "Improved Plumbing": { "Liquid Tuning" },
  "Liquid Tuning": { "Advanced Caffeination" },
  "Advanced Caffeination": { "Jetpacks" },
  "Ventilation": { "Pressure Management", "Portable Gasses" },
  "Pressure Management": { "Temperature Modulation", "Decontamination", "Improved Ventilation" },
  "Temperature Modulation": { "HVAC" },
  "HVAC": { "Catalytics" },
  "Improved Ventilation": { "Hazard Protection" },
  "Hazard Protection": { "Transit Tubes" },
  "Transit Tubes": { "Jetpacks" },
  "Jetpacks": { "Solid Fuel Combustion" },
  "Interior Decor": { "Artistic Expression", "Smart Home" },
  "Artistic Expression": { "Textile Production", "Fine Art" },
  "Textile Production": { "Hazard Protection", "Home Luxuries" },
  "Home Luxuries": { "Glass Blowing" },
  "Glass Blowing": { "Environmental Appreciation", "New Media" },
  "Environmental Appreciation": { "Monuments" },
  "New Media": { "Monuments" },
  "Fine Art": { "High Culture" },
  "High Culture": { "Renaissance Art" },
  "Renaissance Art": { "New Media" },
  "Smart Home": { "Generic Sensors" },
  "Generic Sensors": { "Parallel Automation", "Advanced Automation" },
  "Advanced Automation": { "Computing" },
  "Computing": { "Multiplexing", "Celestial Detection" },
  "Celestial Detection": { "Introductory Rocketry" },
  "Introductory Rocketry": { "Solid Fuel Combustion", "Solid Cargo" },
  "Solid Fuel Combustion": { "Hydrocarbon Combustion" },
  "Hydrocarbon Combustion": { "CryoFuel Combustion" },
  "Solid Cargo": { "Liquid and Gas Cargo" },
  "Liquid and Gas Cargo": { "Unique Cargo" },
}
